### ISSUE TITLE
Lavender Tea has two Farmer's Delight Cooking Pot recipes when it is not needed

### ISSUE THREAD

**Issue by Feranogame** [teamauroramods/Abundance-Forge#17]
Cooking Pot recipes are always shapeless, and Lavender Tea has a Lavender - Leaves and a Leaves - Lavender recipe, which are not both needed as the recipe is shapeless.

**Comment by ex0planetary** [comment]
Not an issue on our end - we've only got one recipe. I think Farmer's Delight + JEI compat might be a bit broken. Will do some testing later and if that's the case I'll send Vector a bug report.
