### ISSUE TITLE
BOP Crafting Recipe Support 

### ISSUE THREAD

**Issue by DereC4** [teamauroramods/Abundance-Forge#18]
Biomes o plenty also uses jacaranda wood and the two mods coexist well. However, I was wondering if this mod could be made compatible with BOP in terms of recipes to make jacaranda wood interchangeable across mods without having to choose one of the other.

**Comment by ex0planetary** [comment]
Seeing as they're independent woodsets having them share recipes would be problematic. We're not gonna add a recipe that can transform one into the other since nobody else really does that - if you want one, you can do that pretty easily with a datapack.

**Comment by DereC4** [comment]
Alright, I've taken your suggestion and created this datapack for it! 
https://www.planetminecraft.com/data-pack/biomes-o-plenty-abundance-jacaranda-conversion-datapack/ 
I was wondering if you could put this somewhere on the website in case anyone wants to have compatibility; if not it's fine.
