### ISSUE TITLE
Redbud leaves incompatible with Better Foliage (Kotlin)

### ISSUE THREAD

**Issue by toErIpNid** [teamauroramods/Abundance-Forge#52]
Redbud leaves do not feature the same 'fuzz" as all the other trees in the world when playing with Better Foliage installed, making them look very out of place.

**Comment by ex0planetary** [comment]
[https://www.curseforge.com/minecraft/texture-packs/aurora-bushy-leaves](https://www.curseforge.com/minecraft/texture-packs/aurora-bushy-leaves)

**Comment by ex0planetary** [comment]
in all seriousness, i'd suggest using this for rough bits of consistency. any issue with the bushiness is an issue on their end since we add redbud leaves the same way every other leaf is coded
