### ISSUE TITLE
Biome doesn't have proper name for map.

### ISSUE THREAD

**Issue by SirChamomile** [teamauroramods/Abundance-Forge#6]
Playing with FTB chunks as my map mod shows me biome.abundance.lavendar_fields.

Also I'm seeing a few trees spawning floating above water.

**Comment by ex0planetary** [comment]
Looks like I forgot to paste the localization for the biome after cutting it. Will fix shortly.

Floating trees are a vanilla bug, blame Mojang. Nothing I can really do about it - if you'd like you could find a mod or datapack to disable the little ponds.

**Comment by ex0planetary** [comment]
Fixed in commit bbb80df
