### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by apimembeku** [teamauroramods/Abundance-Forge#7]
[crash-2021-03-04_15.46.45-fml.txt](https://github.com/teamauroramods/Abundance/files/6082127/crash-2021-03-04_15.46.45-fml.txt)

**Comment by ex0planetary** [comment]
Update Abnormals Core. Will fix required version in mods.toml for all mods in a couple of hours.

**Comment by ex0planetary** [comment]
reopening so I can fix in a pretty commit message
